# Generated by Django 3.2.4 on 2022-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.CharField(max_length=10)),
                ('Cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=20)),
                ('ApellidoUsuario', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=15)),
                ('Usuario', models.EmailField(max_length=30)),
                ('Contrasena', models.CharField(max_length=8)),
            ],
        ),
    ]
